UDF Cancellation
LiberTEM/LiberTEM-live pull request #121
Opened 2023-06-28 09:10 UTC by sk1p

Properly raise `JobCancelledError` if the data stream is interrupted.

## TODO

- [x] Support for DECTRIS
- [x] Support for ASI TPX3
- [ ] Support for QD Merlin

## Contributor Checklist:

* [ ] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [ ] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [ ] I have added/updated documentation for all user-facing changes
* [ ] I have added/updated test cases

## Reviewer Checklist:

* [ ] `/azp run libertem.libertem-live-data` passed

2023-06-28 10:48 UTC, sk1p commented
/azp run libertem.libertem-live-data

2023-06-28 11:30 UTC, sk1p commented
/azp run libertem.libertem-live-data

2023-07-24 15:32 UTC, sk1p commented
/azp run libertem.libertem-live-data

2023-07-24 15:35 UTC, sk1p commented
/azp run libertem.libertem-live-data

2023-07-24 15:38 UTC, sk1p commented on docs/source/examples.rst
> +    :skipif: not HAVE_DECTRIS_TESTDATA or UDFRunCancelled is None
```suggestion
.. code-block:: python
```

Actually, this example is no longer run as part of doc tests, as there's no good way of cancelling the infinite loop without making the example either meaningless or over-complicated, as far as I can see.

2023-07-24 18:28 UTC, sk1p commented
/azp run libertem.libertem-live-data

2023-07-24 18:29 UTC, sk1p commented
/azp run libertem.libertem-live-data

2023-07-25 15:59 UTC, uellue requested changes
Generally, looks good! I'm just wondering why codecov shows the relevant parts of the acquisition object as not covered, despite the tests for it?

2023-07-25 15:59 UTC, uellue commented on src/libertem_live/detectors/asi_tpx3/acquisition.py
> +                    break
Why is Codecov showing this as not covered for all detectors, although you implemented a test for this that uses all detectors?

2023-07-25 15:59 UTC, uellue commented on docs/source/changelog/features/udf-cancellation.rst
> +* Raise a :class:`~libertem.common.executor.JobCancelledError`
The user-facing exception is UDFRunCancelled if I interpret the example correctly?

2023-07-26 08:29 UTC, sk1p commented on src/libertem_live/detectors/asi_tpx3/acquisition.py
> +                    break
I have tests for Merlin and DECTRIS - but they require LiberTEM v0.12 currently. Testing with older LiberTEM would run into quite long timeouts caused by draining the queues after an exception.

We do have the test job in the LiberTEM repository that tests with the LiberTEM-live master branch - maybe we need the symmetric test job here?

A test for ASI TPX3 is a bit harder to write - I'll see if I can force the simulator to reliably cancel in the middle of an acquisition.

2023-07-26 08:32 UTC, sk1p commented on docs/source/changelog/features/udf-cancellation.rst
> +* Raise a :class:`~libertem.common.executor.JobCancelledError`
Right, I'll clarify this.

2023-07-26 09:01 UTC, sk1p commented
/azp run libertem.libertem-live-data

2023-07-26 09:01 UTC, sk1p commented
/azp run libertem.libertem-live-data

2023-07-26 09:09 UTC, sk1p commented
/azp run libertem.libertem-live-data

2023-07-26 10:06 UTC, sk1p commented on src/libertem_live/detectors/asi_tpx3/acquisition.py
> +                    break
> We do have the test job in the LiberTEM repository that tests with the LiberTEM-live master branch - maybe we need the symmetric test job here?

This is now implemented and seems to work.

2023-07-26 10:42 UTC, uellue approved these changes
LGTM! Nice to test against current LiberTEM master. 👍

2023-07-26 10:42 UTC, merged