Update MIB simulator
LiberTEM/LiberTEM-live pull request #159
Opened 2024-07-23 09:51 UTC by sk1p

* Allow multiple acquisitions per connection in triggered mode
* Fix acquisition header and sequence numbers in continuous mode and enforce disabled cache in this case
* More correct control socket handling - read and use the MPX prefix

## Contributor Checklist:

* [ ] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [ ] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [ ] I have added/updated documentation for all user-facing changes
* [ ] I have added/updated test cases

## Reviewer Checklist:

* [ ] `/azp run libertem.libertem-live-data` passed

2024-07-23 09:51 UTC, sk1p commented
/azp run libertem.libertem-live-data

2024-07-23 10:06 UTC, sk1p commented
/azp run libertem.libertem-live-data

2024-07-23 10:21 UTC, sk1p commented
/azp run libertem.libertem-live-data

2024-07-23 11:50 UTC, sk1p commented
/azp run libertem.libertem-live-data

2024-07-23 18:07 UTC, sk1p commented
/azp run libertem.libertem-live-data

2024-07-24 15:54 UTC, sk1p commented
/azp run libertem.libertem-live-data

2024-07-26 12:52 UTC, matbryan52 commented on src/libertem_live/detectors/merlin/sim.py
> +    def send_acquisition_header(self, conn):
The docstring of `HeaderSocketSimulator` still refers to `handle_conn`.

2024-07-26 12:59 UTC, matbryan52 commented on src/libertem_live/detectors/merlin/sim.py
> +    Simulats a "hardware" trigger, meaning an out-of-band signal that
```suggestion
    Simulates a "hardware" trigger, meaning an out-of-band signal that
```

2024-07-26 13:02 UTC, matbryan52 commented on src/libertem_live/detectors/merlin/sim.py
> +    Simulats a "hardware" trigger, meaning an out-of-band signal that
```suggestion
    Simulates a "hardware" trigger, meaning an out-of-band signal that
```

2024-07-26 13:03 UTC, matbryan52 commented on src/libertem_live/detectors/merlin/sim.py
> +    Simulats a "hardware" trigger, meaning an out-of-band signal that
I would add a note in the docstring to distinguish this from the `TriggerSocketServer`, especially as this class is perhaps intended to be used by a user!

2024-07-26 13:27 UTC, matbryan52 commented on src/libertem_live/detectors/merlin/sim.py
> +                if len(mpx_prefix) == 0:
Is it perhaps safer to check we actually received 15 bytes here ? Just so the assumptions about unpacking `p0`, `p1` and that the chunk is the next  data are held.

2024-07-26 13:31 UTC, matbryan52 commented on src/libertem_live/detectors/merlin/sim.py
> +            param = parts[1]
Previously we unpacked items `[2, 3]` from the header+chunk, whereas now it is `3` elements from the header bytes (`p0, p1, _`) and `2` parts from the chunk bytes. Am I wrong in thinking there is an extra element here?

2024-07-26 13:45 UTC, matbryan52 requested changes
I don't know how one would write it but we're missing a test case in `continuous` mode. Is that something that will be easier to add once the dependent PRs are merged?

2024-07-29 06:39 UTC, sk1p commented on src/libertem_live/detectors/merlin/sim.py
> +            frames_per_trigger = 1
I'm not 100% sure about this, as I haven't tested the continuous acquisition ("live view") at a real system in some time. But the way it works from the control side is that you set `NUMFRAMESTOACQUIRE` to zero to continuously acquire data, and at the time the `HDR` is sent over the socket, the number of frames is never known.

So, two assumptions:

1) The `.hdr` file is written at the start of the acquisition and corresponds to the acquisition header that is sent when the detector is armed
2) `Frames in Acquisition (Number)` corresponds directly to `NUMFRAMESTOACQUIRE`

I think that's how it works, but we should test these at the real system.

2024-07-29 06:48 UTC, sk1p commented on src/libertem_live/detectors/merlin/sim.py
> +    Simulats a "hardware" trigger, meaning an out-of-band signal that
I'll reword this part a bit, and remove the redundancy with the server part.

2024-07-29 06:51 UTC, sk1p commented on src/libertem_live/detectors/merlin/sim.py
> +                if len(mpx_prefix) == 0:
I'll add an assertion there, to make sure the length is correct. In theory one would have to loop here until the full 15 bytes have been received, on the other hand, it's unlikely the sending side splits the payload into very small packets...

2024-07-29 07:16 UTC, sk1p commented on src/libertem_live/detectors/merlin/sim.py
> +            param = parts[1]
Let's unpack this a bit... the full input string looks like this:

`"MPX,XXXXXXXXXX,CMD,STARTACQUISITION,0"`

If we split it directly, we get 5 parts, with `CMD` at index 2:

```
In [3]: "MPX,XXXXXXXXXX,CMD,STARTACQUISITION,0".split(",")
Out[3]: ['MPX', 'XXXXXXXXXX', 'CMD', 'STARTACQUISITION', '0']
```

If we now take the `mpx_prefix` only, we get three parts, which is because of the **trailing comma**:

```
In [4]: "MPX,XXXXXXXXXX,".split(",")
Out[4]: ['MPX', 'XXXXXXXXXX', '']
```

And the method, param are in indices 0 and 1:

```
In [5]: "CMD,STARTACQUISITION,0".split(",")
Out[5]: ['CMD', 'STARTACQUISITION', '0']
```

I'll add this example input string as comments, too.

2024-07-29 07:25 UTC, sk1p commented
Thanks for the review!

> I don't know how one would write it but we're missing a test case in `continuous` mode. Is that something that will be easier to add once the dependent PRs are merged?

I also noticed that continuous mode is now one of the last remaining "blind spots" of coverage. And indeed, right now, the client part of continuous mode is only accessible using the low-level APIs, which will be replaced by the rust-based backend, so I'll add a test case in #161.

2024-07-29 07:27 UTC, sk1p commented
/azp run libertem.libertem-live-data

2024-07-29 07:44 UTC, sk1p commented on src/libertem_live/detectors/merlin/sim.py
> +    def send_acquisition_header(self, conn):
Good catch, fixed!

2024-07-29 07:45 UTC, sk1p commented
/azp run libertem.libertem-live-data

2024-07-30 06:47 UTC, matbryan52 commented on src/libertem_live/detectors/merlin/sim.py
> +            frames_per_trigger = 1
I am sure you are right, I am just insufficiently familiar with the system. The thought I had though is that the `Simulator` continuous mode will send the Header at the start of every loop through our file, while the real camera I suppose only sends the header once and then a continuous stream of frames (with no further no headers) ? Is this difference important  for our case?

2024-07-30 06:48 UTC, matbryan52 approved these changes

2024-07-30 06:55 UTC, matbryan52 commented on src/libertem_live/detectors/merlin/sim.py
> +            frames_per_trigger = 1
I just convinced myself that this was not the case !

2024-07-30 07:22 UTC, merged