WIP: DECTRIS: shm-based data handling
LiberTEM/LiberTEM-live pull request #74
Opened 2023-03-15 18:07 UTC by sk1p

Update DECTRIS acquisition to pass data via shared memory to workers; this circumvents costly serialization for moving data between processes and makes it feasible to perform live reconstruction on less powerful systems (i.e. more processing power left over for actual processing versus overheads)

Requires latest `libertem_dectris` release (0.2.4+).

## Contributor Checklist:

* [x] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [ ] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [ ] I have added/updated documentation for all user-facing changes
* [ ] I have added/updated test cases

## Reviewer Checklist:

* [ ] `/azp run libertem.libertem-live-data` passed

2023-03-21 12:37 UTC, sk1p commented
/azp run libertem.libertem-live-data

2023-03-21 12:54 UTC, sk1p commented
/azp run libertem.libertem-live-data

2023-03-30 18:39 UTC, sk1p commented
/azp run libertem.libertem-live-data

2023-04-04 12:05 UTC, sk1p commented
/azp run libertem.libertem-live-data

2023-04-04 15:38 UTC, sk1p commented
/azp run libertem.libertem-live-data

2023-04-05 10:03 UTC, sk1p commented
/azp run libertem.libertem-live-data

2023-04-05 10:42 UTC, sk1p commented
/azp run libertem.libertem-live-data

2023-04-05 11:59 UTC, sk1p commented
/azp run libertem.libertem-live-data

2023-04-06 16:36 UTC, sk1p commented
/azp run libertem.libertem-live-data

2023-04-06 16:52 UTC, sk1p commented
/azp run libertem.libertem-live-data

2023-04-11 13:32 UTC, sk1p commented
/azp run libertem.libertem-live-data

2023-04-11 16:46 UTC, sk1p commented
/azp run libertem.libertem-live-data

2023-04-11 17:12 UTC, sk1p commented
@uellue @matbryan52 this PR is now ready from my side. I realize it is once again more of a feature branch than a single isolated change, but such is the nature if the whole API is revamped...

This should now be more or less stable, and the API changes are done as discussed. I did not yet put more work into getting the merlin part back into feature parity with the DECTRIS part. This is basically #75, and can be done once this is merged, or even after the release. We should probably reserve some time at the HF5000 for this, to check real system behavior.

I'll work next to get the ASI TPX3 stuff into PR form, so we can include it at least as experimental support.

2023-04-11 17:12 UTC, sk1p commented
/azp run libertem.libertem-live-data

2023-04-12 07:47 UTC, matbryan52 commented
> @uellue @matbryan52 this PR is now ready from my side. I realize it is once again more of a feature branch than a single isolated change, but such is the nature if the whole API is revamped...

Great! I've been using the branch for the UI work in the last week, so far good but I still need to integrate the passive / `wait_for_acquisition` mode. I will try to do that today and then look into the PR in more detail.

2023-04-18 11:44 UTC, uellue requested changes
Very nice! Thanks a lot for all this. A number of small comments and suggestions in separate comments. 😄

2023-04-18 11:44 UTC, uellue commented on docs/source/detectors/dectris.rst
> +DECTRIS SIMPLON
Should this also mention the simulator and/or capture tool? We have the simulator documented for Merlin. We could link to https://github.com/LiberTEM/LiberTEM-rs/tree/main/libertem_dectris, perhaps?

2023-04-18 11:44 UTC, uellue commented on docs/source/detectors.rst
>  Supported Detectors
Maybe also briefly mention the memory acquisition here resp. in detectors/*?

2023-04-18 11:44 UTC, uellue commented on src/libertem_live/detectors/merlin/acquisition.py
> +        The number of scan positions as a 2-tuple :code:`(height, width)`
Does it have to be a 2-tuple or can we do n-dimensional acquisitions with DECTRIS?

2023-04-18 11:44 UTC, uellue commented on docs/source/usage.rst
> +Passive mode
Before going into the details of passive and active, maybe a short paragraph on the reasons for this design could help? Here a draft:

### Coordinating live processing

As a general design goal, LiberTEM should behave similarly between offline and live processing. Once created, live acquisition objects can be used like offline datasets. However, the creation process is different: In offline processing, most relevant parameters are pre-determined by an existing dataset, and most datasets share very similar user-controlled parameters. Datasets backed by files can be read at any time and in any sequence.

In contrast, parameters and actions for live processing are dynamic and have to be coordinated correctly in a sequence between microscope, scan engine, detector and LiberTEM processing. Data can only be read sequentially and has to be consumed in a short time window to prevent dropping frames. Furthermore, the parameters and actions can be rather different between different setups and may have to be customized to a higher degree than offline datasets.

Live acquisitions are therefore created in a multi-step procedure to separate concerns of detector interface, detector parameters, hooks for synchronization and customization, and generic LiberTEM parameters. Both an "active mode" where LiberTEM sets parameters and initiates an acquisition, and a "passive mode" where LiberTEM reads parameters and waits for an acquisition are available.

2023-04-18 14:04 UTC, sk1p commented
/azp run libertem.libertem-live-data

2023-04-19 08:11 UTC, uellue commented
LGTM, great! 👍

2023-04-19 08:11 UTC, merged